export const linklatestrelease = "https://api.github.com/repos/AGamingS21/tsqlsharp-formatter-cli/releases/latest";
export const linklinux = "https://github.com/AGamingS21/tsqlsharp-formatter-cli/releases/download/0.0.2/tsqlsharp-formatter-0.0.2-linux-amd64.tar.gz";
export const linkwindows = "https://github.com/AGamingS21/tsqlsharp-formatter-cli/releases/download/0.0.7/tsqlsharp-formatter-0.0.7-windows-amd64.zip";
export const installPath =  '/tsqlsharp';
export const zipFile = installPath + '/tsqlsharp-formatter-0.0.2-linux-amd64.tar.gz';
export const zipFileLinux = installPath + '/tsqlsharp-formatter-0.0.2-linux-amd64.tar.gz';
export const zipFileWindows= installPath + '/tsqlsharp-formatter-0.0.2-linux-amd64.tar.gz';
export const cliPathLinux = installPath + '/tsqlsharp-formatter';
export const cliPathWindows = installPath + '/tsqlsharp-formatter.exe';